# generated by datamodel-codegen:
#   filename:  recursive_container_constraints.json

from __future__ import annotations

from typing import Annotated

from msgspec import UNSET, Meta, Struct, UnsetType


class Node(Struct):
    children: Annotated[list[Node], Meta(max_length=3, min_length=2)] | UnsetType = (
        UNSET
    )
    parent: Node | UnsetType = UNSET
