# generated by datamodel-codegen:
#   filename:  recursive_container_constraints.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field
from pydantic.dataclasses import dataclass


@dataclass
class Node:
    children: Annotated[list[Node] | None, Field(max_length=3, min_length=2)] = None
    parent: Node | None = None
