# generated by datamodel-codegen:
#   filename:  schema_validators_presence_mixed_const.json

from __future__ import annotations

from collections.abc import Mapping as _Mapping
from typing import Any, ClassVar

from pydantic import BaseModel, model_validator


class _JsonSchemaRuntimeValidationBase(BaseModel):
    __json_schema_conditional_required__: ClassVar[tuple[Any, ...]] = ()

    @model_validator(mode='before')
    @classmethod
    def _validate_json_schema_runtime_rules(cls, data: Any) -> Any:
        data = cls._validate_json_schema_conditional_required(data)
        return data

    @classmethod
    def _validate_json_schema_conditional_required(cls, data: Any) -> Any:
        if not (isinstance(data, dict) or isinstance(data, _Mapping)):
            return data
        for rule in cls.__json_schema_conditional_required__:
            condition_matches = all(
                any(
                    name in data
                    and (
                        not expected
                        or data[name] in expected
                    )
                    for name in names
                )
                for names, expected in rule['condition']
            )
            required_groups = (
                rule['then_required_groups']
                if condition_matches
                else rule['else_required_groups']
            )
            for group in required_groups:
                if all(any(name in data for name in names) for names in group):
                    continue
                raise ValueError('Conditional required properties are missing')
        return data


class PresenceRules(_JsonSchemaRuntimeValidationBase):
    __json_schema_conditional_required__: ClassVar[tuple[Any, ...]] = (
        {
            'condition': ((('a',), ()), (('b',), ('x',))),
            'then_required_groups': ((('c',),),),
            'else_required_groups': (),
        },
    )

    guard: int
    a: Any | None = None
    b: Any | None = None
    c: Any | None = None
    d: Any | None = None
