# generated by datamodel-codegen:
#   filename:  schema_validators_not_mixed_rules.json

from __future__ import annotations

from collections.abc import Mapping as _Mapping
from typing import Any, ClassVar

from pydantic import BaseModel, model_validator


class _JsonSchemaRuntimeValidationBase(BaseModel):
    __json_schema_one_of_required_groups__: ClassVar[tuple[Any, ...]] = ()
    __json_schema_any_of_required_groups__: ClassVar[tuple[Any, ...]] = ()
    __json_schema_not_required_groups__: ClassVar[tuple[Any, ...]] = ()
    __json_schema_conditional_required__: ClassVar[tuple[Any, ...]] = ()

    @model_validator(mode='before')
    @classmethod
    def _validate_json_schema_runtime_rules(cls, data: Any) -> Any:
        data = cls._validate_json_schema_required_groups(
            data,
            required_group_rules=cls.__json_schema_one_of_required_groups__,
            require_exactly_one=True,
        )
        data = cls._validate_json_schema_required_groups(
            data,
            required_group_rules=cls.__json_schema_any_of_required_groups__,
            require_exactly_one=False,
        )
        data = cls._validate_json_schema_not_required_groups(data)
        data = cls._validate_json_schema_conditional_required(data)
        return data

    @classmethod
    def _validate_json_schema_required_groups(
        cls,
        data: Any,
        *,
        required_group_rules: tuple[Any, ...],
        require_exactly_one: bool,
    ) -> Any:
        if not required_group_rules:
            return data
        if not (isinstance(data, dict) or isinstance(data, _Mapping)):
            return data
        for required_groups in required_group_rules:
            matches = sum(
                all(any(name in data for name in names) for names in group)
                for group in required_groups
            )
            if require_exactly_one:
                if matches != 1:
                    raise ValueError(
                        'Expected exactly one required property group to be present'
                    )
            elif matches == 0:
                raise ValueError(
                    'Expected at least one required property group to be present'
                )
        return data

    @classmethod
    def _validate_json_schema_not_required_groups(cls, data: Any) -> Any:
        if not (isinstance(data, dict) or isinstance(data, _Mapping)):
            return data
        for required_groups in cls.__json_schema_not_required_groups__:
            for group in required_groups:
                if all(any(name in data for name in names) for names in group):
                    raise ValueError('Expected required property group to be absent')
        return data

    @classmethod
    def _validate_json_schema_conditional_required(cls, data: Any) -> Any:
        if not (isinstance(data, dict) or isinstance(data, _Mapping)):
            return data
        for rule in cls.__json_schema_conditional_required__:
            condition_matches = all(
                any(
                    name in data
                    and (
                        not expected
                        or data[name] in expected
                    )
                    for name in names
                )
                for names, expected in rule['condition']
            )
            required_groups = (
                rule['then_required_groups']
                if condition_matches
                else rule['else_required_groups']
            )
            for group in required_groups:
                if all(any(name in data for name in names) for names in group):
                    continue
                raise ValueError('Conditional required properties are missing')
        return data


class PresenceRules(_JsonSchemaRuntimeValidationBase):
    __json_schema_any_of_required_groups__: ClassVar[tuple[Any, ...]] = (
        ((('c',),), (('d',),)),
    )

    __json_schema_not_required_groups__: ClassVar[tuple[Any, ...]] = (
        ((('a',), ('b',)),),
    )

    __json_schema_conditional_required__: ClassVar[tuple[Any, ...]] = (
        {
            'condition': ((('a',), ()),),
            'then_required_groups': ((('c',),),),
            'else_required_groups': ((('d',),),),
        },
    )

    guard: int
    a: Any | None = None
    b: Any | None = None
    c: Any | None = None
    d: Any | None = None
