# generated by datamodel-codegen:
#   filename:  schema_validators_if_non_object_type.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class PresenceRules(BaseModel):
    guard: int
    a: Any | None = None
    b: Any | None = None
    c: Any | None = None
    d: Any | None = None
