# generated by datamodel-codegen:
#   filename:  schema_validators_not_request.json

from __future__ import annotations

from collections.abc import Mapping as _Mapping
from typing import Any, ClassVar

from pydantic import BaseModel, model_validator


class _JsonSchemaRuntimeValidationBase(BaseModel):
    __json_schema_not_required_groups__: ClassVar[tuple[Any, ...]] = ()

    @model_validator(mode='before')
    @classmethod
    def _validate_json_schema_runtime_rules(cls, data: Any) -> Any:
        data = cls._validate_json_schema_not_required_groups(data)
        return data

    @classmethod
    def _validate_json_schema_not_required_groups(cls, data: Any) -> Any:
        if not (isinstance(data, dict) or isinstance(data, _Mapping)):
            return data
        for required_groups in cls.__json_schema_not_required_groups__:
            for group in required_groups:
                if all(any(name in data for name in names) for names in group):
                    raise ValueError('Expected required property group to be absent')
        return data


class PresenceRulesRequest(BaseModel):
    guard: int
    a: Any | None = None
    b: Any | None = None
    c: Any | None = None
    d: Any | None = None


class PresenceRules(_JsonSchemaRuntimeValidationBase):
    __json_schema_not_required_groups__: ClassVar[tuple[Any, ...]] = (
        ((('id',),),),
    )

    guard: int
    a: Any | None = None
    b: Any | None = None
    c: Any | None = None
    d: Any | None = None
    id: int | None = None
