# generated by datamodel-codegen:
#   filename:  schema_validators_dynamic_empty.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class PresenceRules(BaseModel):
    guard: int
    a: Any | None = None
    b: Any | None = None
