# generated by datamodel-codegen:
#   filename:  mapping_alias_module_split.json

from __future__ import annotations

from typing import Any

from pydantic import RootModel


class Model(RootModel[Any]):
    root: Any
