"""Exercise explicit API declaration collection through real model generation."""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from datamodel_code_generator import DataModelType, Error, InputFileType, OpenAPIScope, SchemaParseError, generate
from datamodel_code_generator.enums import AllExportsScope, JsonSchemaVersion, OpenAPIVersion
from datamodel_code_generator.format import Formatter
from datamodel_code_generator.parser.openapi import OpenAPIParser
from datamodel_code_generator.parser.openapi_scope import ApiModelResolver, ApiOpenAPIParser
from tests.conftest import assert_directory_content, assert_inputs_not_mutated, assert_output

if TYPE_CHECKING:
    from collections.abc import Sequence

    from datamodel_code_generator._source import YamlValue
    from datamodel_code_generator.parser.jsonschema import JsonSchemaObject

DATA = Path(__file__).parents[1] / "data"
SOURCE = DATA / "generation_platform/api_scope"
EXPECTED = DATA / "expected/main/generation_platform/api_scope"


@pytest.mark.parametrize("backend", list(DataModelType))
def test_api_facade_backends(backend: DataModelType) -> None:
    """Compare API collection with a handwritten schema inventory generated by fixed main."""
    result = generate(
        SOURCE / "declarations.json",
        input_file_type=InputFileType.OpenAPI,
        openapi_scopes=[OpenAPIScope.Api],
        output_model_type=backend,
        disable_timestamp=True,
        input_filename="api.json",
        use_operation_id_as_name=True,
        formatters=[Formatter.BLACK, Formatter.ISORT],
    )
    assert_output(result, EXPECTED / (backend.value.replace(".", "_") + ".py"))


def test_api_external_declaration() -> None:
    """Keep external document-local types and both root uses of one Path Item."""
    parser = ApiOpenAPIParser(SOURCE / "external.json", openapi_scopes=[OpenAPIScope.Api], formatters=[])
    try:
        assert_output(parser.parse(), EXPECTED / "external.py")
        assert_output(
            json.dumps(
                [
                    {"use": [use.document, *use.tokens], "declaration": [declaration.document, *declaration.tokens]}
                    for use, declaration, _ in parser.declaration_uses
                ],
                indent=2,
            )
            + "\n",
            EXPECTED / "external-uses.txt",
        )
        assert_output(
            json.dumps(
                {
                    "media_item_schema": parser.schema_features.media_item_schema,
                    "ref_siblings": parser._ref_sibling_keywords_enabled,
                    "root_version": parser.raw_obj["openapi"],
                    "frames": len(parser.declaration_frames),
                },
                indent=2,
            )
            + "\n",
            EXPECTED / "external-state.txt",
        )
    finally:
        parser.dispose()


@pytest.mark.parametrize("dot", [False, True])
@pytest.mark.parametrize("exports", [None, *AllExportsScope])
@pytest.mark.parametrize("existing", [False, True])
def test_api_empty_inventory(dot: bool, exports: AllExportsScope | None, existing: bool, tmp_path: Path) -> None:
    """Emit empty metadata while leaving an absent or existing output untouched."""
    output = tmp_path / "models.py"
    metadata = tmp_path / "metadata.json"
    if existing:
        output.write_bytes((EXPECTED / "existing-output.txt").read_bytes())
    result = generate(
        SOURCE / "contentless.json",
        input_file_type=InputFileType.OpenAPI,
        openapi_scopes=[OpenAPIScope.Api],
        output=output,
        emit_model_metadata=metadata,
        treat_dot_as_module=dot,
        all_exports_scope=exports,
        formatters=[],
        disable_timestamp=True,
    )
    assert_output(metadata.read_text(), EXPECTED / "empty-metadata.txt")
    assert_output(
        json.dumps({"result": result, "output_exists": output.exists()}, indent=2) + "\n",
        EXPECTED / f"empty-state-{existing}.txt",
    )
    if existing:
        assert_output(output.read_text(), EXPECTED / "existing-output.txt")


def test_api_info_version_without_models(tmp_path: Path) -> None:
    """Preserve actual info-version artifacts when the model inventory is empty."""
    output = tmp_path / "package"
    generate(
        SOURCE / "contentless.json",
        input_file_type=InputFileType.OpenAPI,
        openapi_scopes=[OpenAPIScope.Api],
        output=output,
        treat_dot_as_module=True,
        openapi_include_info_version=True,
        formatters=[],
        disable_timestamp=True,
    )
    assert_output((output / "__init__.py").read_text(), EXPECTED / "info-version.py")


@pytest.mark.parametrize(
    "scopes",
    [
        [OpenAPIScope.Api],
        [OpenAPIScope.Api, OpenAPIScope.Schemas, OpenAPIScope.Paths, OpenAPIScope.Parameters, OpenAPIScope.Api],
        list(OpenAPIScope),
        list(reversed(OpenAPIScope)),
        [*OpenAPIScope, *OpenAPIScope],
    ],
)
@pytest.mark.parametrize("repeated", [False, True])
def test_api_declarations(scopes: list[OpenAPIScope], repeated: bool) -> None:
    """Generate all declarations once while retaining ordinary parameter overrides."""
    source = SOURCE / "declarations.json"
    parser = ApiOpenAPIParser(
        [source, source] if repeated else source,
        openapi_scopes=scopes,
        use_operation_id_as_name=True,
        formatters=[],
        base_path=SOURCE,
    )
    try:
        result = parser.parse()
        assert_output(
            result["declarations.py",].body if isinstance(result, dict) else result, EXPECTED / "declarations.py"
        )
        assert_output(
            json.dumps(
                {
                    "foo_name": parser.model_resolver.references["declarations.json#/components/schemas/Foo"].name,
                    "frames": len(parser.declaration_frames),
                    "discriminator_documents": len(parser._discriminator_documents),
                },
                indent=2,
            )
            + "\n",
            EXPECTED / "declarations-state.txt",
        )
    finally:
        parser.dispose()


@pytest.mark.parametrize(
    ("parser_type", "scopes", "message"),
    [
        (OpenAPIParser, [OpenAPIScope.Api], "OpenAPIScope.Api requires ApiOpenAPIParser"),
        (ApiOpenAPIParser, [OpenAPIScope.Schemas], "ApiOpenAPIParser requires OpenAPIScope.Api"),
    ],
)
def test_api_parser_scope_mismatch(parser_type: type[OpenAPIParser], scopes: list[OpenAPIScope], message: str) -> None:
    """Reject incompatible parser selection before parsing input."""
    with pytest.raises(Error, match=message):
        parser_type(SOURCE / "declarations.json", openapi_scopes=scopes)


@pytest.mark.parametrize("version", ["30", "31", "32"])
def test_api_media_applicability(version: str) -> None:
    """Generate only applicable encoding headers, without fetching ignored refs."""
    source = SOURCE / f"media-{version}.json"
    assert_output(
        generate(
            source,
            input_file_type=InputFileType.OpenAPI,
            openapi_scopes=[OpenAPIScope.Api],
            input_filename="media.json",
            disable_timestamp=True,
            formatters=[Formatter.BLACK, Formatter.ISORT],
        ),
        EXPECTED / f"media-{version}.py",
    )
    parser = ApiOpenAPIParser(source, openapi_scopes=[OpenAPIScope.Api], formatters=[])
    try:
        parser.parse()
        assert_output(
            json.dumps(
                [
                    {
                        "tokens": list(item.declaration.tokens),
                        "reason": item.reason,
                        "owner": item.owner,
                        "media": item.media,
                        "wire_name": item.wire_name,
                        "has_operation_owner": item.use_site is not None,
                    }
                    for item in parser.ignored_declarations
                ],
                indent=2,
            )
            + "\n",
            EXPECTED / f"media-{version}-ignored.txt",
        )
        frames_before_dispose = len(parser.declaration_frames)
    finally:
        parser.dispose()
    assert_output(
        json.dumps(
            {
                "frames_before_dispose": frames_before_dispose,
                "ignored_after_dispose": len(parser.ignored_declarations),
                "documents_after_dispose": len(parser.model_resolver.loaded_documents),
            },
            indent=2,
        )
        + "\n",
        EXPECTED / "released-state.txt",
    )


@pytest.mark.parametrize(("case", "message"), json.loads((SOURCE / "invalid-cases.json").read_text()).items())
def test_api_invalid_declarations(case: str, message: str) -> None:
    """Reject malformed declarations at their actual location through the facade."""
    with pytest.raises(SchemaParseError, match=message):
        generate(
            SOURCE / f"{case}.json",
            input_file_type=InputFileType.OpenAPI,
            openapi_scopes=[OpenAPIScope.Api, OpenAPIScope.Tags],
            formatters=[],
            disable_timestamp=True,
        )


@pytest.mark.parametrize("filtered", [False, True])
def test_api_callback_cycle_and_root_filter(filtered: bool) -> None:
    """Traverse cyclic callbacks once and keep webhooks/components outside root filters."""
    assert_output(
        generate(
            SOURCE / "traversal.json",
            input_file_type=InputFileType.OpenAPI,
            openapi_scopes=[OpenAPIScope.Api],
            openapi_include_paths=["/root"] if filtered else None,
            use_title_as_name=True,
            include_path_parameters=False,
            disable_timestamp=True,
            formatters=[Formatter.BLACK, Formatter.ISORT],
        ),
        EXPECTED / ("traversal-filtered.py" if filtered else "traversal.py"),
    )


def test_api_pointer_spellings() -> None:
    """Keep raw percent, tilde, URL and slash declarations distinct through forward refs."""
    assert_output(
        generate(
            SOURCE / "pointer-spellings.json",
            input_file_type=InputFileType.OpenAPI,
            openapi_scopes=[OpenAPIScope.Api],
            use_title_as_name=True,
            disable_timestamp=True,
            formatters=[Formatter.BLACK, Formatter.ISORT],
        ),
        EXPECTED / "pointer-spellings.py",
    )


@pytest.mark.parametrize("case", ["items-primitive", "items-object", "methods-32"])
def test_api_openapi_32_declarations(case: str) -> None:
    """Generate shared item declarations and version-permitted operation schemas."""
    assert_output(
        generate(
            SOURCE / f"{case}.json",
            input_file_type=InputFileType.OpenAPI,
            openapi_scopes=[OpenAPIScope.Api],
            disable_timestamp=True,
            formatters=[Formatter.BLACK, Formatter.ISORT],
        ),
        EXPECTED / f"{case}.py",
    )


def test_api_external_root_and_reserved_definitions() -> None:
    """Keep the existing external root, reserved refs, definitions, and recursive closure."""
    assert_output(
        generate(
            SOURCE / "resources.json",
            input_file_type=InputFileType.OpenAPI,
            openapi_scopes=[OpenAPIScope.Api],
            disable_timestamp=True,
            formatters=[Formatter.BLACK, Formatter.ISORT],
        ),
        EXPECTED / "resources.py",
    )


@pytest.mark.parametrize("case", ["local-roots", "anchors"])
def test_api_local_roots_and_named_ids(case: str) -> None:
    """Delegate local roots, deferred pointers, and named IDs to the model engine."""
    assert_output(
        generate(
            SOURCE / f"{case}.json",
            input_file_type=InputFileType.OpenAPI,
            openapi_scopes=[OpenAPIScope.Api],
            disable_timestamp=True,
            formatters=[Formatter.BLACK, Formatter.ISORT],
        ),
        EXPECTED / f"{case}.py",
    )


@pytest.mark.parametrize("raw_text", [False, True])
def test_api_memory_source(raw_text: bool) -> None:
    """Preserve mapping inputs and the same model bytes across source forms."""
    raw = json.loads((SOURCE / "declarations.json").read_text())
    with assert_inputs_not_mutated({"source": raw}):
        assert_output(
            generate(
                json.dumps(raw) if raw_text else raw,
                input_file_type=InputFileType.OpenAPI,
                openapi_scopes=[OpenAPIScope.Api],
                input_filename="api.json",
                use_operation_id_as_name=True,
                disable_timestamp=True,
                formatters=[Formatter.BLACK, Formatter.ISORT],
            ),
            EXPECTED / "pydantic_v2_BaseModel.py",
        )


@pytest.mark.parametrize("exports", [None, *AllExportsScope])
def test_api_nonempty_dot_modules(exports: AllExportsScope | None, tmp_path: Path) -> None:
    """Use ordinary dot postprocessing and exports for a nonempty result tree."""
    output = tmp_path / "package"
    generate(
        SOURCE / "dot.json",
        input_file_type=InputFileType.OpenAPI,
        openapi_scopes=[OpenAPIScope.Api],
        treat_dot_as_module=True,
        all_exports_scope=exports,
        disable_timestamp=True,
        formatters=[Formatter.BLACK, Formatter.ISORT],
        output=output,
    )
    assert_directory_content(output, EXPECTED / f"dot-{exports.value if exports else 'none'}")


def test_api_discriminator_canonical_parent() -> None:
    """Retain one parent/subtype edge while distinguishing a literal percent key."""
    assert_output(
        generate(
            SOURCE / "discriminator.json",
            input_file_type=InputFileType.OpenAPI,
            openapi_scopes=[OpenAPIScope.Api],
            use_title_as_name=True,
            disable_timestamp=True,
            formatters=[Formatter.BLACK, Formatter.ISORT],
        ),
        EXPECTED / "discriminator.py",
    )
    parser = ApiOpenAPIParser(SOURCE / "discriminator.json", openapi_scopes=[OpenAPIScope.Api], formatters=[])
    try:
        parser.parse()
        assert_output(
            json.dumps(
                {
                    "subtypes": parser._discriminator_subtypes["discriminator.json#/components/schemas/Pet"],
                    "literal_percent_declaration": "discriminator.json#/components/schemas/%2550et"
                    in parser.model_resolver.references,
                    "use_types": len(parser._declaration_types),
                },
                indent=2,
            )
            + "\n",
            EXPECTED / "discriminator-state.txt",
        )
    finally:
        parser.dispose()


def test_api_missing_operation_id() -> None:
    """Preserve the operation-ID option's established error text."""
    with pytest.raises(Error, match="All operations must have an operationId"):
        generate(
            SOURCE / "traversal.json",
            input_file_type=InputFileType.OpenAPI,
            openapi_scopes=[OpenAPIScope.Api],
            use_operation_id_as_name=True,
            formatters=[],
        )


def test_api_reference_leaf_extension() -> None:
    """Keep actual source mappings available to an existing reference-leaf extension."""

    class LeafConsumer(ApiOpenAPIParser):
        same_mapping = False

        def _parse_specification(self, specification: dict[str, YamlValue], path_parts: list[str]) -> None:
            super()._parse_specification(specification, path_parts)
            self.same_mapping = (
                self.get_ref_model("#/components/parameters/Page") is specification["components"]["parameters"]["Page"]
            )

    parser = LeafConsumer(
        SOURCE / "declarations.json", openapi_scopes=[OpenAPIScope.Api], use_operation_id_as_name=True, formatters=[]
    )
    try:
        assert_output(parser.parse(), EXPECTED / "declarations.py")
        assert_output(json.dumps(parser.same_mapping) + "\n", EXPECTED / "leaf-mapping.txt")
    finally:
        parser.dispose()


@pytest.mark.parametrize("case", ["local", "external", "relative", "url", "scoped", "bare", "empty", "many_ordinary"])
def test_api_external_discriminator_regressions(case: str, tmp_path: Path) -> None:
    """Reuse independent legacy goldens for discriminator resource and URL ownership."""
    source = DATA / "openapi/external_discriminator_base"
    output = tmp_path / "models.py"
    generate(
        source / f"{case}.json",
        input_file_type=InputFileType.OpenAPI,
        openapi_scopes=[OpenAPIScope.Api],
        disable_timestamp=True,
        formatters=[Formatter.BLACK, Formatter.ISORT],
        output=output,
        allow_remote_refs=case in {"bare", "empty"},
        http_local_ref_path=source / "mirror" if case == "url" else None,
    )
    assert_output(output.read_text(), DATA / "expected/main/openapi/external_discriminator_base" / f"{case}.py")


@pytest.mark.parametrize("status_names", [False, True])
def test_api_response_headers(status_names: bool) -> None:
    """Keep status-specific header names, boolean schemas, and ordinary allOf behavior."""
    assert_output(
        generate(
            SOURCE / "headers.json",
            input_file_type=InputFileType.OpenAPI,
            openapi_scopes=[OpenAPIScope.Api],
            use_status_code_in_response_name=status_names,
            disable_timestamp=True,
            formatters=[Formatter.BLACK, Formatter.ISORT],
        ),
        EXPECTED / "headers.py",
    )


def test_api_rejects_lost_declaration_frame() -> None:
    """Fail closed if an extension forwards a schema under an unowned path."""

    class LostFrameParser(ApiOpenAPIParser):
        def parse_obj(self, name: str, obj: JsonSchemaObject, path: list[str]) -> None:
            super().parse_obj(name, obj, [*path, "unowned"])

    parser = LostFrameParser(SOURCE / "declarations.json", openapi_scopes=[OpenAPIScope.Api], formatters=[])
    try:
        with pytest.raises(SchemaParseError, match="API_DECLARATION_CONTEXT_REQUIRED"):
            parser.parse()
        assert_output(json.dumps(len(parser.declaration_frames)) + "\n", EXPECTED / "empty-frames.txt")
    finally:
        parser.dispose()


def test_api_rejects_unresolved_anchor_from_resolver() -> None:
    """Reject an abnormal resolver result instead of inferring a declaration."""

    class BrokenResolver(ApiModelResolver):
        def resolve_ref(self, path: Sequence[str] | str) -> str:  # noqa: ARG002
            return "reference-cycle.json#missing"

    class BrokenResolverParser(ApiOpenAPIParser):
        _model_resolver_factory = staticmethod(BrokenResolver)

    parser = BrokenResolverParser(SOURCE / "reference-cycle.json", openapi_scopes=[OpenAPIScope.Api], formatters=[])
    try:
        with pytest.raises(SchemaParseError, match="API_DECLARATION_CONTEXT_REQUIRED"):
            parser.parse()
        assert_output(json.dumps(len(parser.declaration_frames)) + "\n", EXPECTED / "empty-frames.txt")
    finally:
        parser.dispose()


@pytest.mark.parametrize("mode", ["first", "reversed", "directory", "explicit"])
def test_api_root_feature_lifetime(mode: str) -> None:
    """Keep independent dialect caches at the first root, honoring explicit overrides."""
    directory = SOURCE / "version-roots"
    sources = sorted(directory.glob("*.json"), reverse=mode == "reversed")
    parser = ApiOpenAPIParser(
        directory if mode == "directory" else sources,
        openapi_scopes=[OpenAPIScope.Api],
        openapi_version=OpenAPIVersion.V32 if mode == "explicit" else OpenAPIVersion.Auto,
        jsonschema_version=JsonSchemaVersion.Draft202012 if mode == "explicit" else JsonSchemaVersion.Auto,
        formatters=[],
    )
    try:
        result = parser.parse()
        assert_output(
            json.dumps(
                {
                    "media_item_schema": parser.schema_features.media_item_schema,
                    "ref_siblings": parser._ref_sibling_keywords_enabled,
                    "frames": len(parser.declaration_frames),
                    "result": result,
                },
                indent=2,
            )
            + "\n",
            EXPECTED / f"version-{'first' if mode == 'directory' else mode}.txt",
        )
    finally:
        parser.dispose()


@pytest.mark.parametrize("version", ["30", "31"])
def test_api_external_root_dialect(version: str) -> None:
    """Borrow a bare external library only after establishing the root's dialect."""
    parser = ApiOpenAPIParser(SOURCE / f"external-{version}.json", openapi_scopes=[OpenAPIScope.Api], formatters=[])
    try:
        assert_output(parser.parse(), EXPECTED / "external.py")
        assert_output(
            json.dumps(
                {
                    "media_item_schema": parser.schema_features.media_item_schema,
                    "ref_siblings": parser._ref_sibling_keywords_enabled,
                    "frames": len(parser.declaration_frames),
                    "result": {},
                },
                indent=2,
            )
            + "\n",
            EXPECTED / "version-first.txt",
        )
    finally:
        parser.dispose()


@pytest.mark.parametrize("backend", list(DataModelType))
def test_api_native_types_and_ref_siblings(backend: DataModelType) -> None:
    """Preserve Python reuse and schema siblings using an independent fixed-main inventory."""
    assert_output(
        generate(
            SOURCE / "typed-reuse.json",
            input_file_type=InputFileType.OpenAPI,
            openapi_scopes=[OpenAPIScope.Api],
            output_model_type=backend,
            type_overrides={"CustomType": "my_app.types.CustomType"},
            disable_timestamp=True,
            formatters=[Formatter.BLACK, Formatter.ISORT],
        ),
        EXPECTED / f"typed-reuse-{backend.name}.py",
    )


@pytest.mark.parametrize("case", ["header-identity", "method-case"])
def test_api_case_sensitive_declarations(case: str) -> None:
    """Preserve HTTP method casing, header spelling, and case-sensitive query identities."""
    assert_output(
        generate(
            SOURCE / f"{case}.json",
            input_file_type=InputFileType.OpenAPI,
            openapi_scopes=[OpenAPIScope.Api],
            use_operation_id_as_name=True,
            disable_timestamp=True,
            formatters=[Formatter.BLACK, Formatter.ISORT],
        ),
        EXPECTED / f"{case}.py",
    )
