# generated by datamodel-codegen:
#   filename:  collapse_root_models_array_item_union_self_reference.json

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Leaf(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: float


class Model(BaseModel):
    all: All


class All(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    all: Annotated[Sequence[Leaf | All], Field(min_length=2)]


Model.model_rebuild()
All.model_rebuild()
