# generated by datamodel-codegen:
#   filename:  dot.json

from __future__ import annotations

from pydantic import BaseModel

from . import alpha


class Bar(BaseModel):
    foo: alpha.Foo | None = None
