# generated by datamodel-codegen:
#   filename:  anchors.json

from __future__ import annotations

from pydantic import BaseModel, RootModel


class AnchorsLibrary(BaseModel):
    self: AnchorsLibrary | None = None
    value: str | None = None


class Root(RootModel[AnchorsLibrary]):
    root: AnchorsLibrary


AnchorsLibrary.model_rebuild()