# generated by datamodel-codegen:
#   filename:  api.json

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import TypeAlias


@dataclass
class Foo:
    id: int | None = None


class Unused(Enum):
    available = 'available'
    missing = 'missing'


PageParameter: TypeAlias = int


TraceHeader: TypeAlias = str


ListPetsQueryLimitParameter: TypeAlias = int