# generated by datamodel-codegen:
#   filename:  discriminator.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Pet(BaseModel):
    kind: str


class Kind(Enum):
    cat = 'cat'


class Cat(Pet):
    kind: Kind
    lives: int | None = None


class PercentPet(BaseModel):
    literal: bool | None = None