# generated by datamodel-codegen:
#   filename:  headers.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, RootModel


class Free(RootModel[Any]):
    root: Any


class Never(RootModel[Any]):
    root: Any


class Normal(BaseModel):
    value: str | None = None


class AllOfNoRef(BaseModel):
    number: int | None = None


class Derived(Normal):
    pass


class SharedResponseXComponentHeader(RootModel[str]):
    root: str


class FieldItemsGetResponse200XTraceHeader(RootModel[bool]):
    root: bool


class FieldItemsGetResponse201XTraceHeader(RootModel[int]):
    root: int