# generated by datamodel-codegen:
#   filename:  header-identity.json

from __future__ import annotations

from enum import Enum


class CaseGetHeaderXCamelTraceParameter(Enum):
    active = 'active'


class CaseGetHeaderAnotherCamelParameter(Enum):
    preserved = 'preserved'


class CaseGetQueryQParameter(Enum):
    upper = 'upper'


class CaseGetQueryQParameter1(Enum):
    lower = 'lower'