# generated by datamodel-codegen:
#   filename:  items-object.json

from __future__ import annotations

from pydantic import BaseModel, RootModel


class EventsRequestItem(BaseModel):
    value: int | None = None


class EventsRequest(RootModel[list[EventsRequestItem]]):
    root: list[EventsRequestItem]