# generated by datamodel-codegen:
#   filename:  items-primitive.json

from __future__ import annotations

from pydantic import RootModel


class EventsRequestItem(RootModel[int]):
    root: int


class EventsRequest(RootModel[list[EventsRequestItem]]):
    root: list[EventsRequestItem]