# generated by datamodel-codegen:
#   filename:  local-roots.json

from __future__ import annotations

from pydantic import BaseModel


class LocalRoots(BaseModel):
    root: str | None = None


class Local(BaseModel):
    value: str | None = None


class Uses(BaseModel):
    root: LocalRoots | None = None
    local: Local | None = None