# generated by datamodel-codegen:
#   filename:  media.json

from __future__ import annotations

from pydantic import BaseModel, RootModel


class ContentParameterPartXParameterEncodingHeader(BaseModel):
    trace: str | None = None


class UploadRequestPartXRequestEncodingHeader(BaseModel):
    trace: str | None = None


class ResultResponsePartXResponseEncodingHeader(BaseModel):
    trace: str | None = None


class SharedHeader(RootModel[int]):
    root: int


class ContentTypeHeader(RootModel[str]):
    root: str


class ContentHeaderPartXHeaderEncodingHeader(BaseModel):
    trace: str | None = None