# generated by datamodel-codegen:
#   filename:  methods-32.json

from __future__ import annotations

from pydantic import BaseModel, RootModel


class FieldSearchQueryQuerystring(BaseModel):
    value: int | None = None


class FieldSearchCopyRequest(RootModel[str]):
    root: str