# generated by datamodel-codegen:
#   filename:  method-case.json

from __future__ import annotations

from enum import Enum


class FixedGetResponse(Enum):
    standard = 'standard'


class LowerGetResponse(Enum):
    lower = 'lower'


class MixedGetResponse(Enum):
    mixed = 'mixed'


class LowerQueryResponse(Enum):
    querylower = 'querylower'