# generated by datamodel-codegen:
#   filename:  api.json

from __future__ import annotations

from enum import Enum
from typing import TypeAlias

from msgspec import UNSET, Struct, UnsetType


class Foo(Struct):
    id: int | UnsetType = UNSET


class Unused(Enum):
    available = 'available'
    missing = 'missing'


PageParameter: TypeAlias = int


TraceHeader: TypeAlias = str


ListPetsQueryLimitParameter: TypeAlias = int