# generated by datamodel-codegen:
#   filename:  pointer-spellings.json

from __future__ import annotations

from pydantic import BaseModel, Field


class Plain(BaseModel):
    value: str | None = None
    field_: int | None = Field(None, alias='')


class PercentSlash(BaseModel):
    value: str | None = None
    field_: int | None = Field(None, alias='')


class TildeOne(BaseModel):
    value: str | None = None
    field_: int | None = Field(None, alias='')


class Slash(BaseModel):
    value: str | None = None
    field_: int | None = Field(None, alias='')


class Url(BaseModel):
    value: str | None = None
    field_: int | None = Field(None, alias='')


class Identifier(BaseModel):
    value: str | None = None
    field_: int | None = Field(None, alias='')


class Percent(BaseModel):
    value: str | None = None
    field_: int | None = Field(None, alias='')


class Tilde(BaseModel):
    value: str | None = None
    field_: int | None = Field(None, alias='')


class Uses(BaseModel):
    plain: Plain | None = None
    percentslash: PercentSlash | None = None
    tildeone: TildeOne | None = None
    slash: Slash | None = None
    url: Url | None = None
    identifier: Identifier | None = None
    percent: Percent | None = None
    tilde: Tilde | None = None
    alias: Plain | None = None