# generated by datamodel-codegen:
#   filename:  api.json

from __future__ import annotations

from enum import Enum

from pydantic.dataclasses import dataclass
from typing_extensions import TypeAliasType


@dataclass
class Foo:
    id: int | None = None


class Unused(Enum):
    available = 'available'
    missing = 'missing'


PageParameter = TypeAliasType("PageParameter", int)


TraceHeader = TypeAliasType("TraceHeader", str)


ListPetsQueryLimitParameter = TypeAliasType("ListPetsQueryLimitParameter", int)