# generated by datamodel-codegen:
#   filename:  api.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, RootModel


class Foo(BaseModel):
    id: int | None = None


class Unused(Enum):
    available = 'available'
    missing = 'missing'


class PageParameter(RootModel[int]):
    root: int


class TraceHeader(RootModel[str]):
    root: str


class ListPetsQueryLimitParameter(RootModel[int]):
    root: int