# generated by datamodel-codegen:
#   filename:  resources.json

from __future__ import annotations

from pydantic import BaseModel


class Later(BaseModel):
    value: int | None = None


class ResourcesLibrary(BaseModel):
    nested: Later | None = None
    self: ResourcesLibrary | None = None


class Selected(BaseModel):
    root: ResourcesLibrary | None = None
    late: Later | None = None


class Uses(BaseModel):
    selected: Selected | None = None
    root: ResourcesLibrary | None = None


ResourcesLibrary.model_rebuild()