# generated by datamodel-codegen:
#   filename:  traversal.json

from __future__ import annotations

from pydantic import BaseModel


class OperationQuery(BaseModel):
    value: str | None = None


class OperationPath(BaseModel):
    value: str | None = None


class CommonHeader(BaseModel):
    value: str | None = None


class RootRequest(BaseModel):
    value: str | None = None


class RootResponse(BaseModel):
    value: str | None = None


class CallbackRequest(BaseModel):
    value: str | None = None


class OverriddenGlobal(BaseModel):
    value: str | None = None


class LiteralRoot(BaseModel):
    value: str | None = None


class WebhookX(BaseModel):
    value: str | None = None


class WebhookSlashX(BaseModel):
    value: str | None = None


class UnusedPathItem(BaseModel):
    value: str | None = None


class UnusedCallback(BaseModel):
    value: str | None = None