# generated by datamodel-codegen:
#   filename:  typed-reuse.json

from __future__ import annotations

from typing import TypedDict
from uuid import UUID

from my_app.types import CustomType
from typing_extensions import NotRequired


class Base(TypedDict):
    id: NotRequired[int]
    native: NotRequired[UUID]
    custom: NotRequired[CustomType]


class FieldGetResponse(TypedDict):
    id: NotRequired[int]
    native: NotRequired[UUID]
    custom: NotRequired[CustomType]
    extra: NotRequired[str]