# generated by datamodel-codegen:
#   filename:  typed-reuse.json

from __future__ import annotations

from uuid import UUID

from msgspec import UNSET, Struct, UnsetType
from my_app.types import CustomType


class Base(Struct):
    id: int | UnsetType = UNSET
    native: UUID | UnsetType = UNSET
    custom: CustomType | UnsetType = UNSET


class FieldGetResponse(Struct):
    id: int | UnsetType = UNSET
    native: UUID | UnsetType = UNSET
    custom: CustomType | UnsetType = UNSET
    extra: str | UnsetType = UNSET