# generated by datamodel-codegen:
#   filename:  typed-reuse.json

from __future__ import annotations

from uuid import UUID

from my_app.types import CustomType
from pydantic import BaseModel


class Base(BaseModel):
    id: int | None = None
    native: UUID | None = None
    custom: CustomType | None = None


class FieldGetResponse(BaseModel):
    id: int | None = None
    native: UUID | None = None
    custom: CustomType | None = None
    extra: str | None = None