# generated by datamodel-codegen:
#   filename:  api.json

from __future__ import annotations

from typing import Literal, TypeAlias, TypedDict

from typing_extensions import NotRequired


class Foo(TypedDict):
    id: NotRequired[int]


Unused: TypeAlias = Literal['available', 'missing']


PageParameter: TypeAlias = int


TraceHeader: TypeAlias = str


ListPetsQueryLimitParameter: TypeAlias = int